morse_dict = {
    "0": "-----",
    "1": ".----",
    "2": "..---",
    "3": "...--",
    "4": "....-",
    "5": ".....",
    "6": "-....",
    "7": "--...",
    "8": "---..",
    "9": "----.",
    "a": ".-",
    "b": "-...",
    "c": "-.-.",
    "d": "-..",
    "e": ".",
    "f": "..-.",
    "g": "--.",
    "h": "....",
    "i": "..",
    "j": ".---",
    "k": "-.-",
    "l": ".-..",
    "m": "--",
    "n": "-.",
    "o": "---",
    "p": ".--.",
    "q": "--.-",
    "r": ".-.",
    "s": "...",
    "t": "-",
    "u": "..-",
    "v": "...-",
    "w": ".--",
    "x": "-..-",
    "y": "-.--",
    "z": "--..",
    ".": ".-.-.-",
    ",": "--..--",
    "?": "..--..",
    "!": "-.-.--",
    "-": "-....-",
    "/": "-..-.",
    "@": ".--.-.",
    "(": "-.--.",
    ")": "-.--.-"
}

# word_list = ['committee', 'need', 'level']

word_list = ['committee', 'need', 'level', 'print',
             'wandering', 'weight', 'visitor', 'sprout',
             'violent', 'hungry', 'fertile', 'puzzling',
             'close', 'chubby', 'ritzy', 'exultant',
             'cemetery', 'awful', 'quack', 'breathe',
             'box', 'discover', 'concerned', 'reason',
             'pray', 'cracker', 'electric', 'connect',
             'punch', 'married']

# choice = int(input())
# print(word_list[0:choice])
